[package]
name = "tui-molviz"
version = "0.3.0"
authors = ["William Bro-Jørgensen"]
edition = "2024"
rust-version = "1.88.0"
description = "A molecular visualizer widget for Ratatui"
readme = "README.md"
repository = "https://github.com/chem-william/tui-molviz"
license = "MIT"
keywords = ["ratatui", "chemistry", "tui", "visualization", "molecule"]
categories = ["science", "command-line-utilities"]
exclude = [".github/", "assets/", ".gitignore"]

[dependencies]
mendeleev = "0.8.4"
ratatui = "0.30.2"
thiserror = "2.0.19"

[dev-dependencies]
color-eyre = "0.6.5"
